/**
 * ============================================================================
 * ZIP80 - BUILD CONFIGURATION SCRIPT
 * ============================================================================
 * 
 * PURPOSE:
 * Generates src/js/config.js from environment variables before build.
 * This keeps sensitive API keys out of source control.
 * 
 * USAGE:
 * 1. Copy .env.example to .env and fill in your values
 * 2. Run: node scripts/build-config.js
 * 3. The generated config.js is gitignored
 * 
 * CHANGE LOG:
 * - 2025-12-20: Initial creation for Client ID injection
 * ============================================================================
 */

const fs = require('fs');
const path = require('path');

// Try to load dotenv if available
try {
    require('dotenv').config();
} catch (e) {
    // dotenv not installed, use process.env directly
}

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;

if (!GOOGLE_CLIENT_ID) {
    console.error('ERROR: GOOGLE_CLIENT_ID not found in environment.');
    console.error('Please create a .env file with GOOGLE_CLIENT_ID=your-client-id');
    process.exit(1);
}

const configContent = `/**
 * ============================================================================
 * ZIP80 - RUNTIME CONFIGURATION (AUTO-GENERATED)
 * ============================================================================
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * This file is generated by scripts/build-config.js
 * 
 * To regenerate: node scripts/build-config.js
 * ============================================================================
 */

const Config = (() => {
    return {
        GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
    };
})();
`;

const outputPath = path.join(__dirname, '..', 'src', 'js', 'config.js');

fs.writeFileSync(outputPath, configContent, 'utf-8');
console.log('✅ Generated config.js with Client ID');
